import type { AchievementDef } from '../types';

// ===========================================================================
// Achievements — each earned one grants a small, permanent, STACKING global
// production multiplier (its `bonus`). Exploration quietly compounds. They
// survive prestige (they're a measure of you, not the run).
// ===========================================================================

export const ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'ach-curtain-up',
    name: 'Curtain Up',
    description: 'Dispatch your very first coaster.',
    condition: { kind: 'lifetime', currency: 'zoomies', amount: 1 },
    bonus: 1.02,
  },
  {
    id: 'ach-bravo',
    name: 'Bravo!',
    description: 'Earn your first Bravo.',
    condition: { kind: 'lifetime', currency: 'bravos', amount: 1 },
    bonus: 1.02,
  },
  {
    id: 'ach-full-house',
    name: 'Full House',
    description: 'Own 50 generators at once.',
    condition: { kind: 'totalGenerators', amount: 50 },
    bonus: 1.03,
  },
  {
    id: 'ach-sold-out',
    name: 'Sold Out',
    description: 'Own 200 generators at once.',
    condition: { kind: 'totalGenerators', amount: 200 },
    bonus: 1.05,
  },
  {
    id: 'ach-standing-room',
    name: 'Standing Room Only',
    description: 'Own 500 generators at once.',
    condition: { kind: 'totalGenerators', amount: 500 },
    bonus: 1.08,
  },
  {
    id: 'ach-six-figures',
    name: 'Six-Figure Zoomies',
    description: 'Reach 100,000 lifetime zoomies.',
    condition: { kind: 'lifetime', currency: 'zoomies', amount: 1e5 },
    bonus: 1.03,
  },
  {
    id: 'ach-millionaire',
    name: 'Zoomie Millionaire',
    description: 'Reach 1,000,000 lifetime zoomies.',
    condition: { kind: 'lifetime', currency: 'zoomies', amount: 1e6 },
    bonus: 1.04,
  },
  {
    id: 'ach-billionaire',
    name: 'Zoomie Billionaire',
    description: 'Reach 1,000,000,000 lifetime zoomies.',
    condition: { kind: 'lifetime', currency: 'zoomies', amount: 1e9 },
    bonus: 1.05,
  },
  {
    id: 'ach-trillionaire',
    name: 'Cosmic Bookkeeping',
    description: 'Reach 1,000,000,000,000 lifetime zoomies.',
    condition: { kind: 'lifetime', currency: 'zoomies', amount: 1e12 },
    bonus: 1.07,
  },
  {
    id: 'ach-fueled',
    name: 'Fully Fueled',
    description: 'Reach Act Two and produce Kibble.',
    condition: { kind: 'lifetime', currency: 'kibble', amount: 1000 },
    bonus: 1.03,
  },
  {
    id: 'ach-greenhouse',
    name: 'Industrial Morale',
    description: 'Own 25 Catnip Greenhouses.',
    condition: { kind: 'owned', generator: 'p2-catnip-greenhouse', amount: 25 },
    bonus: 1.04,
  },
  {
    id: 'ach-harmony',
    name: 'In Perfect Harmony',
    description: 'Produce 10,000 lifetime G-Force.',
    condition: { kind: 'lifetime', currency: 'gforce', amount: 1e4 },
    bonus: 1.05,
  },
  {
    id: 'ach-tension',
    name: 'The Held Breath',
    description: 'Produce 10,000 lifetime Dramatic Tension.',
    condition: { kind: 'lifetime', currency: 'tension', amount: 1e4 },
    bonus: 1.05,
  },
  {
    id: 'ach-strata',
    name: 'Touching the Sky',
    description: 'Own 50 Strata-Coasters.',
    condition: { kind: 'owned', generator: 'p3-strata-coaster', amount: 50 },
    bonus: 1.06,
  },
  {
    id: 'ach-moonshot',
    name: 'Moonshot',
    description: 'Earn your first Moonlight.',
    condition: { kind: 'lifetime', currency: 'moonlight', amount: 1 },
    bonus: 1.05,
  },
  {
    id: 'ach-to-the-moon',
    name: 'To The Moon, Literally',
    description: 'Reach 100,000 lifetime Moonlight.',
    condition: { kind: 'lifetime', currency: 'moonlight', amount: 1e5 },
    bonus: 1.08,
  },
  {
    id: 'ach-first-cut',
    name: "The Director's Cut",
    description: 'Prestige for the first time.',
    condition: { kind: 'prestiges', amount: 1 },
    bonus: 1.1,
  },
  {
    id: 'ach-auteur',
    name: 'Auteur',
    description: 'Prestige 3 times.',
    condition: { kind: 'prestiges', amount: 3 },
    bonus: 1.12,
  },
  {
    id: 'ach-legend',
    name: 'Living Legend',
    description: 'Prestige 10 times.',
    condition: { kind: 'prestiges', amount: 10 },
    bonus: 1.2,
  },
  {
    id: 'ach-finale',
    name: 'The Grand Finale',
    description: 'Reach Act Four — Interstellar.',
    condition: { kind: 'phase', phase: 4 },
    bonus: 1.1,
  },

  // === EXPANSION achievements ============================================
  {
    id: 'ach-quadrillion',
    name: 'Quadrillion Club',
    description: 'Reach 1e15 lifetime zoomies.',
    condition: { kind: 'lifetime', currency: 'zoomies', amount: 1e15 },
    bonus: 1.08,
  },
  {
    id: 'ach-quintillion',
    name: 'Numbers Stop Meaning Things',
    description: 'Reach 1e18 lifetime zoomies.',
    condition: { kind: 'lifetime', currency: 'zoomies', amount: 1e18 },
    bonus: 1.1,
  },
  {
    id: 'ach-zoomie-god',
    name: 'Zoomie Deity',
    description: 'Reach 1e24 lifetime zoomies.',
    condition: { kind: 'lifetime', currency: 'zoomies', amount: 1e24 },
    bonus: 1.15,
  },
  {
    id: 'ach-bravo-mogul',
    name: 'Acclaim Mogul',
    description: 'Reach 1e12 lifetime Bravos.',
    condition: { kind: 'lifetime', currency: 'bravos', amount: 1e12 },
    bonus: 1.08,
  },
  {
    id: 'ach-fuel-baron',
    name: 'Fuel Baron',
    description: 'Reach 1e9 lifetime Kibble.',
    condition: { kind: 'lifetime', currency: 'kibble', amount: 1e9 },
    bonus: 1.06,
  },
  {
    id: 'ach-gforce-master',
    name: 'Master of Force',
    description: 'Reach 1e9 lifetime G-Force.',
    condition: { kind: 'lifetime', currency: 'gforce', amount: 1e9 },
    bonus: 1.07,
  },
  {
    id: 'ach-tension-master',
    name: 'Master of Feeling',
    description: 'Reach 1e9 lifetime Dramatic Tension.',
    condition: { kind: 'lifetime', currency: 'tension', amount: 1e9 },
    bonus: 1.07,
  },
  {
    id: 'ach-moon-baron',
    name: 'Lord of the Tides',
    description: 'Reach 1e9 lifetime Moonlight.',
    condition: { kind: 'lifetime', currency: 'moonlight', amount: 1e9 },
    bonus: 1.1,
  },
  {
    id: 'ach-mega-park',
    name: 'A Park of One’s Own',
    description: 'Own 1,000 generators at once.',
    condition: { kind: 'totalGenerators', amount: 1000 },
    bonus: 1.12,
  },
  {
    id: 'ach-vertigo',
    name: 'Don’t Look Down',
    description: 'Own 25 Vertigo Towers.',
    condition: { kind: 'owned', generator: 'p3-vertigo-tower', amount: 25 },
    bonus: 1.06,
  },
  {
    id: 'ach-ringmaster',
    name: 'Send in the Robots',
    description: 'Own 25 Robo-Ringmasters.',
    condition: { kind: 'owned', generator: 'p2-robo-ringmaster', amount: 25 },
    bonus: 1.05,
  },
  {
    id: 'ach-wormhole',
    name: 'Closed Timelike Curtain Call',
    description: 'Own 10 Wormhole Junctions.',
    condition: { kind: 'owned', generator: 'p4-wormhole-junction', amount: 10 },
    bonus: 1.08,
  },
  {
    id: 'ach-veteran-director',
    name: 'Seasoned Auteur',
    description: 'Prestige 25 times.',
    condition: { kind: 'prestiges', amount: 25 },
    bonus: 1.25,
  },
  {
    id: 'ach-eternal-director',
    name: 'The Eternal Director',
    description: 'Prestige 50 times.',
    condition: { kind: 'prestiges', amount: 50 },
    bonus: 1.3,
  },
  {
    id: 'ach-finale-act4',
    name: 'Beyond the Kármán Line',
    description: 'Own 25 Giga-Coasters.',
    condition: { kind: 'owned', generator: 'p4-giga-coaster', amount: 25 },
    bonus: 1.09,
  },
];

export const ACHIEVEMENT_META: Record<string, AchievementDef> = Object.fromEntries(
  ACHIEVEMENTS.map((a) => [a.id, a]),
);
