import type { AchievementDef } from '../types';

// ===========================================================================
// Achievements — each earned one grants a small, permanent, STACKING global
// production multiplier (its `bonus`). Exploration quietly compounds. They
// survive prestige (they're a measure of you, not the run).
// ===========================================================================

export const ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'ach-curtain-up',
    name: 'Curtain Up',
    description: 'Raise the curtain on your very first scene.',
    condition: { kind: 'lifetime', currency: 'zoomies', amount: 1 },
    bonus: 1.02,
  },
  {
    id: 'ach-bravo',
    name: 'Bravo!',
    description: 'Earn your first Bravo.',
    condition: { kind: 'lifetime', currency: 'bravos', amount: 1 },
    bonus: 1.02,
  },
  {
    id: 'ach-full-house',
    name: 'Full House',
    description: 'Own 50 generators at once.',
    condition: { kind: 'totalGenerators', amount: 50 },
    bonus: 1.03,
  },
  {
    id: 'ach-sold-out',
    name: 'Sold Out',
    description: 'Own 200 generators at once.',
    condition: { kind: 'totalGenerators', amount: 200 },
    bonus: 1.05,
  },
  {
    id: 'ach-standing-room',
    name: 'Standing Room Only',
    description: 'Own 500 generators at once.',
    condition: { kind: 'totalGenerators', amount: 500 },
    bonus: 1.08,
  },
  {
    id: 'ach-six-figures',
    name: 'Six-Figure Buzz',
    description: 'Reach 100,000 lifetime Buzz.',
    condition: { kind: 'lifetime', currency: 'zoomies', amount: 1e5 },
    bonus: 1.03,
  },
  {
    id: 'ach-millionaire',
    name: 'Buzz Millionaire',
    description: 'Reach 1,000,000 lifetime Buzz.',
    condition: { kind: 'lifetime', currency: 'zoomies', amount: 1e6 },
    bonus: 1.04,
  },
  {
    id: 'ach-billionaire',
    name: 'Buzz Billionaire',
    description: 'Reach 1,000,000,000 lifetime Buzz.',
    condition: { kind: 'lifetime', currency: 'zoomies', amount: 1e9 },
    bonus: 1.05,
  },
  {
    id: 'ach-trillionaire',
    name: 'Cosmic Bookkeeping',
    description: 'Reach 1,000,000,000,000 lifetime Buzz.',
    condition: { kind: 'lifetime', currency: 'zoomies', amount: 1e12 },
    bonus: 1.07,
  },
  {
    id: 'ach-fueled',
    name: 'Fully Fueled',
    description: 'Reach Act Two and brew Coffee.',
    condition: { kind: 'lifetime', currency: 'kibble', amount: 1000 },
    bonus: 1.03,
  },
  {
    id: 'ach-greenhouse',
    name: 'Industrial Morale',
    description: 'Own 25 Green Rooms.',
    condition: { kind: 'owned', generator: 'p2-catnip-greenhouse', amount: 25 },
    bonus: 1.04,
  },
  {
    id: 'ach-harmony',
    name: 'In Perfect Harmony',
    description: 'Produce 10,000 lifetime Comedy.',
    condition: { kind: 'lifetime', currency: 'gforce', amount: 1e4 },
    bonus: 1.05,
  },
  {
    id: 'ach-tension',
    name: 'The Held Breath',
    description: 'Produce 10,000 lifetime Tragedy.',
    condition: { kind: 'lifetime', currency: 'tension', amount: 1e4 },
    bonus: 1.05,
  },
  {
    id: 'ach-strata',
    name: 'Touching the Sky',
    description: 'Own 50 Main Stages.',
    condition: { kind: 'owned', generator: 'p3-strata-coaster', amount: 50 },
    bonus: 1.06,
  },
  {
    id: 'ach-moonshot',
    name: 'In the Limelight',
    description: 'Earn your first Limelight.',
    condition: { kind: 'lifetime', currency: 'moonlight', amount: 1 },
    bonus: 1.05,
  },
  {
    id: 'ach-to-the-moon',
    name: 'To The Moon, Literally',
    description: 'Reach 100,000 lifetime Limelight.',
    condition: { kind: 'lifetime', currency: 'moonlight', amount: 1e5 },
    bonus: 1.08,
  },
  {
    id: 'ach-first-cut',
    name: 'The Revival',
    description: 'Prestige for the first time.',
    condition: { kind: 'prestiges', amount: 1 },
    bonus: 1.1,
  },
  {
    id: 'ach-auteur',
    name: 'Auteur',
    description: 'Prestige 3 times.',
    condition: { kind: 'prestiges', amount: 3 },
    bonus: 1.12,
  },
  {
    id: 'ach-legend',
    name: 'Living Legend',
    description: 'Prestige 10 times.',
    condition: { kind: 'prestiges', amount: 10 },
    bonus: 1.2,
  },
  {
    id: 'ach-finale',
    name: 'The Grand Finale',
    description: 'Reach Act Four — Interstellar.',
    condition: { kind: 'phase', phase: 4 },
    bonus: 1.1,
  },

  // === EXPANSION achievements ============================================
  {
    id: 'ach-quadrillion',
    name: 'Quadrillion Club',
    description: 'Reach 1e15 lifetime Buzz.',
    condition: { kind: 'lifetime', currency: 'zoomies', amount: 1e15 },
    bonus: 1.08,
  },
  {
    id: 'ach-quintillion',
    name: 'Numbers Stop Meaning Things',
    description: 'Reach 1e18 lifetime Buzz.',
    condition: { kind: 'lifetime', currency: 'zoomies', amount: 1e18 },
    bonus: 1.1,
  },
  {
    id: 'ach-zoomie-god',
    name: 'Buzz Deity',
    description: 'Reach 1e24 lifetime Buzz.',
    condition: { kind: 'lifetime', currency: 'zoomies', amount: 1e24 },
    bonus: 1.15,
  },
  {
    id: 'ach-bravo-mogul',
    name: 'Acclaim Mogul',
    description: 'Reach 1e12 lifetime Bravos.',
    condition: { kind: 'lifetime', currency: 'bravos', amount: 1e12 },
    bonus: 1.08,
  },
  {
    id: 'ach-fuel-baron',
    name: 'Fuel Baron',
    description: 'Reach 1e9 lifetime Coffee.',
    condition: { kind: 'lifetime', currency: 'kibble', amount: 1e9 },
    bonus: 1.06,
  },
  {
    id: 'ach-gforce-master',
    name: 'Master of Mirth',
    description: 'Reach 1e9 lifetime Comedy.',
    condition: { kind: 'lifetime', currency: 'gforce', amount: 1e9 },
    bonus: 1.07,
  },
  {
    id: 'ach-tension-master',
    name: 'Master of Tears',
    description: 'Reach 1e9 lifetime Tragedy.',
    condition: { kind: 'lifetime', currency: 'tension', amount: 1e9 },
    bonus: 1.07,
  },
  {
    id: 'ach-moon-baron',
    name: 'Lord of the Tides',
    description: 'Reach 1e9 lifetime Limelight.',
    condition: { kind: 'lifetime', currency: 'moonlight', amount: 1e9 },
    bonus: 1.1,
  },
  {
    id: 'ach-mega-park',
    name: 'A Theatre of One’s Own',
    description: 'Own 1,000 generators at once.',
    condition: { kind: 'totalGenerators', amount: 1000 },
    bonus: 1.12,
  },
  {
    id: 'ach-vertigo',
    name: 'Don’t Look Down',
    description: 'Own 25 Upper Circles.',
    condition: { kind: 'owned', generator: 'p3-vertigo-tower', amount: 25 },
    bonus: 1.06,
  },
  {
    id: 'ach-ringmaster',
    name: 'Send in the Robots',
    description: 'Own 25 Robo-Stage-Managers.',
    condition: { kind: 'owned', generator: 'p2-robo-ringmaster', amount: 25 },
    bonus: 1.05,
  },
  {
    id: 'ach-wormhole',
    name: 'Closed Timelike Curtain Call',
    description: 'Own 10 Wormhole Wings.',
    condition: { kind: 'owned', generator: 'p4-wormhole-junction', amount: 10 },
    bonus: 1.08,
  },
  {
    id: 'ach-veteran-director',
    name: 'Seasoned Auteur',
    description: 'Prestige 25 times.',
    condition: { kind: 'prestiges', amount: 25 },
    bonus: 1.25,
  },
  {
    id: 'ach-eternal-director',
    name: 'The Eternal Director',
    description: 'Prestige 50 times.',
    condition: { kind: 'prestiges', amount: 50 },
    bonus: 1.3,
  },
  {
    id: 'ach-finale-act4',
    name: 'The Cosmos Sells Out',
    description: 'Own 25 Command Performances.',
    condition: { kind: 'owned', generator: 'p4-giga-coaster', amount: 25 },
    bonus: 1.09,
  },
  {
    id: 'ach-act5',
    name: 'The Show Becomes Aware',
    description: 'Reach Act Five — The Ouroboros.',
    condition: { kind: 'phase', phase: 5 },
    bonus: 1.12,
  },
  {
    id: 'ach-echo-first',
    name: '…first…first…first…',
    description: 'Earn your first Echo.',
    condition: { kind: 'lifetime', currency: 'echoes', amount: 1 },
    bonus: 1.08,
  },
  {
    id: 'ach-echo-baron',
    name: 'Recursion Baron',
    description: 'Reach 1e6 lifetime Echoes.',
    condition: { kind: 'lifetime', currency: 'echoes', amount: 1e6 },
    bonus: 1.12,
  },
  {
    id: 'ach-ouroboros',
    name: 'It Eats Itself',
    description: 'Own 10 Ouroboros stages.',
    condition: { kind: 'owned', generator: 'p5-ouroboros-coaster', amount: 10 },
    bonus: 1.1,
  },
  {
    id: 'ach-mirror-maze',
    name: 'Lost in the Mirrors',
    description: 'Own 50 Halls of Mirrors.',
    condition: { kind: 'owned', generator: 'p5-hall-of-mirrors', amount: 50 },
    bonus: 1.08,
  },
];

export const ACHIEVEMENT_META: Record<string, AchievementDef> = Object.fromEntries(
  ACHIEVEMENTS.map((a) => [a.id, a]),
);
