import type { GeneratorDef } from '../types';

// ===========================================================================
// Generators across all four content phases.
//
// Currency flows are intentionally interlocked so the player keeps making
// decisions:
//   • Phase 1: zoomies (kinetic) + bravos (acclaim from actors/props).
//   • Phase 2: Kibble FUEL — some buildings make it, some burn it. Over-build
//     consumers and they starve. Balance is the game.
//   • Phase 3: G-Force vs Dramatic Tension — kept in harmony, everything sings.
//   • Phase 4: Moonlight — the gateway resonance to the Director's Cut.
//
// Base numbers here are a starting point; the headless simulator (scripts/sim.ts)
// is used to tune them for marathon-idle pacing.
// ===========================================================================

export const GENERATORS: GeneratorDef[] = [
  // --- Phase 1: The Mundane ------------------------------------------------
  {
    id: 'p1-cardboard-hill',
    name: 'Cardboard Hill',
    description: 'A lift hill carved from a delivery box. Humble. Reliable. Slightly damp.',
    phase: 1,
    costCurrency: 'zoomies',
    baseCost: 10,
    costMultiplier: 1.15,
    output: { zoomies: 1 },
  },
  {
    id: 'p1-sofa-airtime',
    name: 'Sofa Cushion Airtime',
    description: 'Launch off the loveseat for a glorious half-second of feline weightlessness.',
    phase: 1,
    costCurrency: 'zoomies',
    baseCost: 110,
    costMultiplier: 1.15,
    output: { zoomies: 8 },
  },
  {
    id: 'p1-understudy-tabby',
    name: 'Understudy Tabby',
    description: 'A nervous tabby who has memorized everyone’s lines. Generates pure acclaim.',
    phase: 1,
    costCurrency: 'zoomies',
    baseCost: 650,
    costMultiplier: 1.16,
    output: { bravos: 1 },
  },
  {
    id: 'p1-yarn-catapult',
    name: 'Yarn Catapult',
    description: 'Converts a ball of yarn into terrifying lateral Gs. The cats adore it.',
    phase: 1,
    costCurrency: 'zoomies',
    baseCost: 1400,
    costMultiplier: 1.15,
    output: { zoomies: 47 },
  },
  {
    id: 'p1-spotlight-rig',
    name: 'Spotlight Rig',
    description: 'A repurposed desk lamp on a broom. Props earn applause AND momentum.',
    phase: 1,
    costCurrency: 'zoomies',
    baseCost: 7800,
    costMultiplier: 1.16,
    output: { zoomies: 30, bravos: 4 },
  },
  {
    id: 'p1-matinee-troupe',
    name: 'Matinee Troupe',
    description: 'Hire a whole troupe with your acclaim; they pack the house and dispatch coasters.',
    phase: 1,
    costCurrency: 'bravos',
    baseCost: 40,
    costMultiplier: 1.17,
    output: { zoomies: 140 },
  },
  {
    id: 'p1-cardboard-loop',
    name: 'Cardboard Loop',
    description: 'A full inversion held together by tape and sheer narrative will.',
    phase: 1,
    costCurrency: 'zoomies',
    baseCost: 16000,
    costMultiplier: 1.15,
    output: { zoomies: 260 },
  },

  // --- Phase 2: The Escalation (Kibble fuel) -------------------------------
  {
    id: 'p2-kibble-dispenser',
    name: 'Kibble Dispenser',
    description: 'A clattering hopper of fuel pellets. The backbone of all automation.',
    phase: 2,
    costCurrency: 'zoomies',
    baseCost: 2e5,
    costMultiplier: 1.15,
    output: { kibble: 6 },
  },
  {
    id: 'p2-litterbox-roomba',
    name: 'Litterbox Roomba',
    description: 'Self-cleaning, self-dispatching. Sips Kibble, returns a torrent of zoomies.',
    phase: 2,
    costCurrency: 'zoomies',
    baseCost: 3.4e5,
    costMultiplier: 1.16,
    output: { zoomies: 5200 },
    consumes: { kibble: 2 },
  },
  {
    id: 'p2-catnip-greenhouse',
    name: 'Catnip Greenhouse',
    description: 'Industrial morale, photosynthesized. Big Kibble output, lightly hallucinogenic.',
    phase: 2,
    costCurrency: 'zoomies',
    baseCost: 2.1e6,
    costMultiplier: 1.16,
    output: { kibble: 70 },
  },
  {
    id: 'p2-timber-coaster',
    name: 'Backyard Timber Coaster',
    description: 'Real wood, real splinters, real airtime. Hungry for fuel.',
    phase: 2,
    costCurrency: 'zoomies',
    baseCost: 1.3e6,
    costMultiplier: 1.15,
    output: { zoomies: 27000, bravos: 12 },
    consumes: { kibble: 3 },
  },
  {
    id: 'p2-press-agent',
    name: 'Feline Press Agent',
    description: 'Spins every derailment into a triumph. Converts acclaim into more acclaim.',
    phase: 2,
    costCurrency: 'bravos',
    baseCost: 2200,
    costMultiplier: 1.18,
    output: { bravos: 95, zoomies: 4200 },
  },
  {
    id: 'p2-conveyor-feeder',
    name: 'Conveyor Feeder',
    description: 'A ravenous automated dispatch line. Astonishing output, astonishing appetite.',
    phase: 2,
    costCurrency: 'kibble',
    baseCost: 5200,
    costMultiplier: 1.15,
    output: { zoomies: 95000 },
    consumes: { kibble: 9 },
  },

  // --- Phase 3: The Absurd (G-Force vs Dramatic Tension) -------------------
  {
    id: 'p3-strata-coaster',
    name: 'Strata-Coaster',
    description: 'Pierces the clouds. Produces G-Force and Tension in perfect, balanced measure.',
    phase: 3,
    costCurrency: 'zoomies',
    baseCost: 5e8,
    costMultiplier: 1.16,
    output: { gforce: 10, tension: 10, zoomies: 2.2e6 },
  },
  {
    id: 'p3-gforce-pylon',
    name: 'G-Force Pylon',
    description: 'Pure crushing acceleration. Skews the balance toward force — use with intent.',
    phase: 3,
    costCurrency: 'zoomies',
    baseCost: 9e8,
    costMultiplier: 1.16,
    output: { gforce: 85 },
  },
  {
    id: 'p3-tension-orchestra',
    name: 'Tension Orchestra',
    description: 'A pit of cats with tiny violins. Skews the balance toward feeling.',
    phase: 3,
    costCurrency: 'bravos',
    baseCost: 5e5,
    costMultiplier: 1.17,
    output: { tension: 85, bravos: 42000 },
  },
  {
    id: 'p3-inertia-flywheel',
    name: 'Inertia Flywheel',
    description: 'Spend hoarded G-Force to fling coasters into staggering zoomie output.',
    phase: 3,
    costCurrency: 'gforce',
    baseCost: 2200,
    costMultiplier: 1.18,
    output: { zoomies: 6.5e7 },
  },
  {
    id: 'p3-method-actor',
    name: 'Method-Actor Cat',
    description: 'Spends Tension to deliver performances that detonate the box office.',
    phase: 3,
    costCurrency: 'tension',
    baseCost: 2200,
    costMultiplier: 1.18,
    output: { zoomies: 5.5e7, bravos: 2.2e5 },
  },
  {
    id: 'p3-harmonic-loop',
    name: 'Harmonic Loop',
    description: 'A figure-eight that breathes. Generates force and feeling together, abundantly.',
    phase: 3,
    costCurrency: 'zoomies',
    baseCost: 1.1e10,
    costMultiplier: 1.15,
    output: { gforce: 420, tension: 420, zoomies: 6e7 },
  },

  // --- Phase 4: Interstellar (Moonlight) -----------------------------------
  {
    id: 'p4-giga-coaster',
    name: 'Giga-Coaster',
    description: 'Leaves the atmosphere. Burns Kibble like a rocket, returns the first Moonlight.',
    phase: 4,
    costCurrency: 'zoomies',
    baseCost: 1e14,
    costMultiplier: 1.16,
    output: { moonlight: 1, zoomies: 1.2e11 },
    consumes: { kibble: 600 },
  },
  {
    id: 'p4-moon-lasso',
    name: 'Moon Lasso',
    description: 'Wraps a coaster clean around the moon. Spend G-Force, harvest Moonlight.',
    phase: 4,
    costCurrency: 'gforce',
    baseCost: 5.5e5,
    costMultiplier: 1.17,
    output: { moonlight: 9, zoomies: 5e11 },
  },
  {
    id: 'p4-black-hole-aria',
    name: 'Black-Hole Aria',
    description: 'The cats sing into the event horizon. The reverb is worth unspeakable acclaim.',
    phase: 4,
    costCurrency: 'tension',
    baseCost: 5.5e5,
    costMultiplier: 1.17,
    output: { moonlight: 13, bravos: 5e9 },
  },
  {
    id: 'p4-orbital-litterbox',
    name: 'Orbital Litterbox',
    description: 'A moon-sized fuel refinery. Spend Moonlight; rain Kibble and zoomies back down.',
    phase: 4,
    costCurrency: 'moonlight',
    baseCost: 55,
    costMultiplier: 1.18,
    output: { kibble: 6e6, zoomies: 1e12 },
  },
  {
    id: 'p4-singing-comet',
    name: 'Singing Comet',
    description: 'A comet on a season pass. Loops the system, compounding its own Moonlight.',
    phase: 4,
    costCurrency: 'moonlight',
    baseCost: 220,
    costMultiplier: 1.18,
    output: { moonlight: 32, zoomies: 5e12 },
  },
  {
    id: 'p4-nebula-amphitheater',
    name: 'Nebula Amphitheater',
    description: 'Seats ten billion. Produces everything at once because, frankly, it can.',
    phase: 4,
    costCurrency: 'zoomies',
    baseCost: 1e16,
    costMultiplier: 1.16,
    output: { moonlight: 65, gforce: 5e5, tension: 5e5, zoomies: 1.4e13 },
  },

  // =========================================================================
  // EXPANSION — deeper ladders for every act. (Appended so each act's new
  // props appear after its originals.)
  // =========================================================================

  // --- Phase 1 extras ------------------------------------------------------
  {
    id: 'p1-curtain-rig',
    name: 'Velvet Curtain Rig',
    description: 'A proper curtain on a pulley. Drama doubles as airtime; the cats demand a fog machine.',
    phase: 1,
    costCurrency: 'zoomies',
    baseCost: 42000,
    costMultiplier: 1.16,
    output: { zoomies: 620, bravos: 5 },
  },
  {
    id: 'p1-prima-donna',
    name: 'Prima Donna Persian',
    description: 'A diva who will only perform stage-left, in soft lighting. Pure, demanding acclaim.',
    phase: 1,
    costCurrency: 'zoomies',
    baseCost: 95000,
    costMultiplier: 1.17,
    output: { bravos: 16 },
  },
  {
    id: 'p1-grand-finale',
    name: 'Living-Room Grand Finale',
    description: 'Every cushion, every cat, every cardboard inch — one enormous closing number.',
    phase: 1,
    costCurrency: 'zoomies',
    baseCost: 380000,
    costMultiplier: 1.15,
    output: { zoomies: 4200 },
  },

  // --- Phase 2 extras ------------------------------------------------------
  {
    id: 'p2-treat-printer',
    name: 'Industrial Treat Printer',
    description: 'Prints Kibble by the pallet. Smells incredible. Legally a "morale device".',
    phase: 2,
    costCurrency: 'zoomies',
    baseCost: 8e6,
    costMultiplier: 1.16,
    output: { kibble: 320 },
  },
  {
    id: 'p2-scratch-skyscraper',
    name: 'Scratching-Post Skyscraper',
    description: 'Forty storeys of sisal and screaming descents. Burns fuel; prints acclaim.',
    phase: 2,
    costCurrency: 'zoomies',
    baseCost: 1.4e7,
    costMultiplier: 1.16,
    output: { zoomies: 380000, bravos: 90 },
    consumes: { kibble: 14 },
  },
  {
    id: 'p2-robo-ringmaster',
    name: 'Robo-Ringmaster',
    description: 'An animatronic top hat that runs the whole yard. Voracious, but magnificent.',
    phase: 2,
    costCurrency: 'kibble',
    baseCost: 22000,
    costMultiplier: 1.16,
    output: { zoomies: 620000, bravos: 200 },
    consumes: { kibble: 22 },
  },

  // --- Phase 3 extras (cross-feed coasters help you hold harmony) ----------
  {
    id: 'p3-vertigo-tower',
    name: 'Vertigo Tower',
    description: 'So tall the cats can see next Tuesday. Generates force and feeling in lockstep.',
    phase: 3,
    costCurrency: 'zoomies',
    baseCost: 6e10,
    costMultiplier: 1.16,
    output: { gforce: 1600, tension: 1600, zoomies: 3e8 },
  },
  {
    id: 'p3-cliffhanger-rig',
    name: 'Cliffhanger Rig',
    description: 'Converts hoarded G-Force into Tension (and a fortune) — a lever to re-balance the act.',
    phase: 3,
    costCurrency: 'gforce',
    baseCost: 9000,
    costMultiplier: 1.18,
    output: { tension: 620, zoomies: 4e8 },
  },
  {
    id: 'p3-soliloquy-engine',
    name: 'Soliloquy Engine',
    description: 'Converts hoarded Tension into G-Force (and a fortune) — the other lever. Balance at will.',
    phase: 3,
    costCurrency: 'tension',
    baseCost: 9000,
    costMultiplier: 1.18,
    output: { gforce: 620, zoomies: 4e8 },
  },

  // --- Phase 4 extras ------------------------------------------------------
  {
    id: 'p4-wormhole-junction',
    name: 'Wormhole Junction',
    description: 'A coaster that exits before it enters. Produces everything, including paradoxes.',
    phase: 4,
    costCurrency: 'zoomies',
    baseCost: 6e16,
    costMultiplier: 1.16,
    output: { moonlight: 240, gforce: 2e6, tension: 2e6, zoomies: 6e13 },
  },
  {
    id: 'p4-galactic-tour-bus',
    name: 'Galactic Tour Bus',
    description: 'Season-pass holders ride the whole arm of the galaxy. Spend G-Force, reap Moonlight & raves.',
    phase: 4,
    costCurrency: 'gforce',
    baseCost: 2e6,
    costMultiplier: 1.17,
    output: { moonlight: 40, bravos: 2e10, zoomies: 2e12 },
  },
  {
    id: 'p4-supernova-encore',
    name: 'Supernova Encore',
    description: 'For the curtain call, a star. Compounds its own Moonlight in a blinding crescendo.',
    phase: 4,
    costCurrency: 'moonlight',
    baseCost: 800,
    costMultiplier: 1.18,
    output: { moonlight: 110, zoomies: 2e13 },
  },

  // --- Phase 5: The Ouroboros (Echoes; some engines burn Moonlight) --------
  {
    id: 'p5-mirror-stage',
    name: 'Mirror Stage',
    description: 'A stage that reflects itself into the wings, into the seats, into next week. The first Echoes.',
    phase: 5,
    costCurrency: 'zoomies',
    baseCost: 1e18,
    costMultiplier: 1.17,
    output: { echoes: 1, zoomies: 2e15 },
  },
  {
    id: 'p5-hall-of-mirrors',
    name: 'Hall of Mirrors',
    description: 'Infinite reflections, infinite encores. Folds Moonlight into pure recursion.',
    phase: 5,
    costCurrency: 'zoomies',
    baseCost: 9e18,
    costMultiplier: 1.17,
    output: { echoes: 7 },
    consumes: { moonlight: 60 },
  },
  {
    id: 'p5-recursive-troupe',
    name: 'Recursive Troupe',
    description: 'A cast that plays the audience watching the cast. Acclaim all the way down.',
    phase: 5,
    costCurrency: 'bravos',
    baseCost: 5e13,
    costMultiplier: 1.18,
    output: { echoes: 9, bravos: 4e12 },
  },
  {
    id: 'p5-fourth-wall',
    name: 'Fourth-Wall Breaker',
    description: 'Spend Echoes to address the audience directly — they rain back zoomies and fresh Moonlight.',
    phase: 5,
    costCurrency: 'echoes',
    baseCost: 2000,
    costMultiplier: 1.18,
    output: { zoomies: 6e16, moonlight: 280 },
  },
  {
    id: 'p5-infinite-encore',
    name: 'Infinite Encore',
    description: 'It will not stop. It cannot stop. Each encore spawns more encores.',
    phase: 5,
    costCurrency: 'echoes',
    baseCost: 8000,
    costMultiplier: 1.18,
    output: { echoes: 95, zoomies: 4e17 },
  },
  {
    id: 'p5-ouroboros-coaster',
    name: 'Ouroboros Coaster',
    description: 'The track is a closed loop that is also the story that is also the track. It produces everything, including itself.',
    phase: 5,
    costCurrency: 'zoomies',
    baseCost: 1e21,
    costMultiplier: 1.17,
    output: { echoes: 650, gforce: 1e8, tension: 1e8, zoomies: 8e18 },
  },
];

export const GENERATOR_META: Record<string, GeneratorDef> = Object.fromEntries(
  GENERATORS.map((g) => [g.id, g]),
);
