import type { GeneratorDef } from '../types';

// ===========================================================================
// Generators across all five content acts.
//
// Currency flows are intentionally interlocked so the player keeps making
// decisions:
//   • Act 1: Buzz (audience electricity) + Bravos (acclaim from props/cast).
//   • Act 2: Coffee FUEL — some rooms make it, some burn it. Over-build the
//     consumers and the crew starves. Balance is the game.
//   • Act 3: Comedy vs Tragedy — the two masks; kept in harmony, everything sings.
//   • Act 4: Limelight — the gateway resonance to the later acts.
//   • Act 5: Echoes — the self-referential meta-theatre.
//
// Base numbers here are a starting point; the headless simulator (scripts/sim.ts)
// is used to tune them for marathon-idle pacing.
// ===========================================================================

export const GENERATORS: GeneratorDef[] = [
  // --- Act 1: The Mundane --------------------------------------------------
  {
    id: 'p1-cardboard-hill',
    name: 'Cardboard Flat',
    description: 'A painted cardboard flat propped against the sofa. Humble. Reliable. Slightly damp.',
    phase: 1,
    costCurrency: 'zoomies',
    baseCost: 10,
    costMultiplier: 1.15,
    output: { zoomies: 1 },
  },
  {
    id: 'p1-sofa-airtime',
    name: 'Sofa Front Row',
    description: 'Loveseat cushions arranged into a front row. Every seat sold (to relatives).',
    phase: 1,
    costCurrency: 'zoomies',
    baseCost: 110,
    costMultiplier: 1.15,
    output: { zoomies: 8 },
  },
  {
    id: 'p1-understudy-tabby',
    name: 'The Understudy',
    description: 'A nervous understudy who has memorized everyone’s lines, including the cut ones. Generates pure acclaim.',
    phase: 1,
    costCurrency: 'zoomies',
    baseCost: 650,
    costMultiplier: 1.16,
    output: { bravos: 1 },
  },
  {
    id: 'p1-yarn-catapult',
    name: 'Confetti Cannon',
    description: 'Converts a spool of ribbon into a terrifying blast of streamers. The cast adores it.',
    phase: 1,
    costCurrency: 'zoomies',
    baseCost: 1400,
    costMultiplier: 1.15,
    output: { zoomies: 47 },
  },
  {
    id: 'p1-spotlight-rig',
    name: 'Spotlight Rig',
    description: 'A repurposed desk lamp on a broom. Props earn applause AND momentum.',
    phase: 1,
    costCurrency: 'zoomies',
    baseCost: 7800,
    costMultiplier: 1.16,
    output: { zoomies: 30, bravos: 4 },
  },
  {
    id: 'p1-matinee-troupe',
    name: 'Matinee Troupe',
    description: 'Hire a whole troupe with your acclaim; they pack the house and take the stage.',
    phase: 1,
    costCurrency: 'bravos',
    baseCost: 40,
    costMultiplier: 1.17,
    output: { zoomies: 140 },
  },
  {
    id: 'p1-cardboard-loop',
    name: 'Painted Backdrop',
    description: 'A full painted backdrop held up by tape and sheer narrative will.',
    phase: 1,
    costCurrency: 'zoomies',
    baseCost: 16000,
    costMultiplier: 1.15,
    output: { zoomies: 260 },
  },

  // --- Act 2: The Escalation (Coffee fuel) ---------------------------------
  {
    id: 'p2-kibble-dispenser',
    name: 'Coffee Urn',
    description: 'A clattering urn of crew-grade coffee. The backbone of all automation.',
    phase: 2,
    costCurrency: 'zoomies',
    baseCost: 2e5,
    costMultiplier: 1.15,
    output: { kibble: 6 },
  },
  {
    id: 'p2-litterbox-roomba',
    name: 'Roving Stagehand',
    description: 'Self-directing, tireless. Sips Coffee, returns a torrent of Buzz.',
    phase: 2,
    costCurrency: 'zoomies',
    baseCost: 3.4e5,
    costMultiplier: 1.16,
    output: { zoomies: 5200 },
    consumes: { kibble: 2 },
  },
  {
    id: 'p2-catnip-greenhouse',
    name: 'Green Room',
    description: 'Industrial morale, brewed and catered. Big Coffee output, faint smell of hairspray.',
    phase: 2,
    costCurrency: 'zoomies',
    baseCost: 2.1e6,
    costMultiplier: 1.16,
    output: { kibble: 70 },
  },
  {
    id: 'p2-timber-coaster',
    name: 'Hand-Built Proscenium',
    description: 'Real wood, real splinters, real drama. Hungry for Coffee.',
    phase: 2,
    costCurrency: 'zoomies',
    baseCost: 1.3e6,
    costMultiplier: 1.15,
    output: { zoomies: 27000, bravos: 12 },
    consumes: { kibble: 3 },
  },
  {
    id: 'p2-press-agent',
    name: 'Press Agent',
    description: 'Spins every flubbed line into a triumph. Converts acclaim into more acclaim.',
    phase: 2,
    costCurrency: 'bravos',
    baseCost: 2200,
    costMultiplier: 1.18,
    output: { bravos: 95, zoomies: 4200 },
  },
  {
    id: 'p2-conveyor-feeder',
    name: 'Overnight Crew',
    description: 'A ravenous automated stage crew. Astonishing output, astonishing appetite.',
    phase: 2,
    costCurrency: 'kibble',
    baseCost: 5200,
    costMultiplier: 1.15,
    output: { zoomies: 95000 },
    consumes: { kibble: 9 },
  },

  // --- Act 3: The Absurd (Comedy vs Tragedy) -------------------------------
  {
    id: 'p3-strata-coaster',
    name: 'The Main Stage',
    description: 'Pierces the very ceiling of the artform. Produces Comedy and Tragedy in perfect, balanced measure.',
    phase: 3,
    costCurrency: 'zoomies',
    baseCost: 5e8,
    costMultiplier: 1.16,
    output: { gforce: 10, tension: 10, zoomies: 2.2e6 },
  },
  {
    id: 'p3-gforce-pylon',
    name: 'Comedy Cannon',
    description: 'Pure, crushing hilarity. Skews the balance toward Comedy — use with intent.',
    phase: 3,
    costCurrency: 'zoomies',
    baseCost: 9e8,
    costMultiplier: 1.16,
    output: { gforce: 85 },
  },
  {
    id: 'p3-tension-orchestra',
    name: 'Tragedy Orchestra',
    description: 'A pit of violinists with tiny, devastating bows. Skews the balance toward Tragedy.',
    phase: 3,
    costCurrency: 'bravos',
    baseCost: 5e5,
    costMultiplier: 1.17,
    output: { tension: 85, bravos: 42000 },
  },
  {
    id: 'p3-inertia-flywheel',
    name: 'Slapstick Flywheel',
    description: 'Spend hoarded Comedy to fling the ensemble into staggering Buzz.',
    phase: 3,
    costCurrency: 'gforce',
    baseCost: 2200,
    costMultiplier: 1.18,
    output: { zoomies: 6.5e7 },
  },
  {
    id: 'p3-method-actor',
    name: 'Method Actor',
    description: 'Spends Tragedy to deliver performances that detonate the box office.',
    phase: 3,
    costCurrency: 'tension',
    baseCost: 2200,
    costMultiplier: 1.18,
    output: { zoomies: 5.5e7, bravos: 2.2e5 },
  },
  {
    id: 'p3-harmonic-loop',
    name: 'The Tragicomedy',
    description: 'A play that breathes between laughter and tears. Generates Comedy and Tragedy together, abundantly.',
    phase: 3,
    costCurrency: 'zoomies',
    baseCost: 1.1e10,
    costMultiplier: 1.15,
    output: { gforce: 420, tension: 420, zoomies: 6e7 },
  },

  // --- Act 4: Interstellar (Limelight) -------------------------------------
  {
    id: 'p4-giga-coaster',
    name: 'Command Performance',
    description: 'The show leaves the atmosphere to play for the cosmos. Burns Coffee like a rocket, returns the first Limelight.',
    phase: 4,
    costCurrency: 'zoomies',
    baseCost: 1e14,
    costMultiplier: 1.16,
    output: { moonlight: 1, zoomies: 1.2e11 },
    consumes: { kibble: 600 },
  },
  {
    id: 'p4-moon-lasso',
    name: 'Lunar Curtain Call',
    description: 'A bow so grand the moon returns for it. Spend Comedy, harvest Limelight.',
    phase: 4,
    costCurrency: 'gforce',
    baseCost: 5.5e5,
    costMultiplier: 1.17,
    output: { moonlight: 9, zoomies: 5e11 },
  },
  {
    id: 'p4-black-hole-aria',
    name: 'Black-Hole Aria',
    description: 'The ensemble sings a high C into the event horizon. The reverb is worth unspeakable acclaim.',
    phase: 4,
    costCurrency: 'tension',
    baseCost: 5.5e5,
    costMultiplier: 1.17,
    output: { moonlight: 13, bravos: 5e9 },
  },
  {
    id: 'p4-orbital-litterbox',
    name: 'Orbital Green Room',
    description: 'A moon-sized catering satellite. Spend Limelight; rain Coffee and Buzz back down.',
    phase: 4,
    costCurrency: 'moonlight',
    baseCost: 55,
    costMultiplier: 1.18,
    output: { kibble: 6e6, zoomies: 1e12 },
  },
  {
    id: 'p4-singing-comet',
    name: 'Singing Comet',
    description: 'A comet on a residency. Loops the system, compounding its own Limelight.',
    phase: 4,
    costCurrency: 'moonlight',
    baseCost: 220,
    costMultiplier: 1.18,
    output: { moonlight: 32, zoomies: 5e12 },
  },
  {
    id: 'p4-nebula-amphitheater',
    name: 'Nebula Amphitheatre',
    description: 'Seats ten billion. Produces everything at once because, frankly, it can.',
    phase: 4,
    costCurrency: 'zoomies',
    baseCost: 1e16,
    costMultiplier: 1.16,
    output: { moonlight: 65, gforce: 5e5, tension: 5e5, zoomies: 1.4e13 },
  },

  // =========================================================================
  // EXPANSION — deeper ladders for every act. (Appended so each act's new
  // props appear after its originals.)
  // =========================================================================

  // --- Act 1 extras --------------------------------------------------------
  {
    id: 'p1-curtain-rig',
    name: 'Velvet Curtain Rig',
    description: 'A proper velvet curtain on a pulley. Drama doubles as spectacle; the cast demands a fog machine.',
    phase: 1,
    costCurrency: 'zoomies',
    baseCost: 42000,
    costMultiplier: 1.16,
    output: { zoomies: 620, bravos: 5 },
  },
  {
    id: 'p1-prima-donna',
    name: 'Prima Donna',
    description: 'A diva who will only perform stage-left, in soft lighting. Pure, demanding acclaim.',
    phase: 1,
    costCurrency: 'zoomies',
    baseCost: 95000,
    costMultiplier: 1.17,
    output: { bravos: 16 },
  },
  {
    id: 'p1-grand-finale',
    name: 'Living-Room Grand Finale',
    description: 'Every cushion, every prop, every square inch of carpet — one enormous closing number.',
    phase: 1,
    costCurrency: 'zoomies',
    baseCost: 380000,
    costMultiplier: 1.15,
    output: { zoomies: 4200 },
  },

  // --- Act 2 extras --------------------------------------------------------
  {
    id: 'p2-treat-printer',
    name: 'Catering Truck',
    description: 'Prints Coffee and sandwiches by the pallet. Legally a "morale device".',
    phase: 2,
    costCurrency: 'zoomies',
    baseCost: 8e6,
    costMultiplier: 1.16,
    output: { kibble: 320 },
  },
  {
    id: 'p2-scratch-skyscraper',
    name: 'Fly Tower',
    description: 'Forty storeys of rigging and screaming set-changes. Burns Coffee; prints acclaim.',
    phase: 2,
    costCurrency: 'zoomies',
    baseCost: 1.4e7,
    costMultiplier: 1.16,
    output: { zoomies: 380000, bravos: 90 },
    consumes: { kibble: 14 },
  },
  {
    id: 'p2-robo-ringmaster',
    name: 'Robo-Stage-Manager',
    description: 'An animatronic clipboard that runs the whole house. Voracious, but magnificent.',
    phase: 2,
    costCurrency: 'kibble',
    baseCost: 22000,
    costMultiplier: 1.16,
    output: { zoomies: 620000, bravos: 200 },
    consumes: { kibble: 22 },
  },

  // --- Act 3 extras (cross-feed levers help you hold harmony) --------------
  {
    id: 'p3-vertigo-tower',
    name: 'The Upper Circle',
    description: 'So high the ensemble can see next Tuesday. Generates Comedy and Tragedy in lockstep.',
    phase: 3,
    costCurrency: 'zoomies',
    baseCost: 6e10,
    costMultiplier: 1.16,
    output: { gforce: 1600, tension: 1600, zoomies: 3e8 },
  },
  {
    id: 'p3-cliffhanger-rig',
    name: 'Cliffhanger',
    description: 'Converts hoarded Comedy into Tragedy (and a fortune) — a lever to re-balance the act.',
    phase: 3,
    costCurrency: 'gforce',
    baseCost: 9000,
    costMultiplier: 1.18,
    output: { tension: 620, zoomies: 4e8 },
  },
  {
    id: 'p3-soliloquy-engine',
    name: 'Soliloquy Engine',
    description: 'Converts hoarded Tragedy into Comedy (and a fortune) — the other lever. Balance at will.',
    phase: 3,
    costCurrency: 'tension',
    baseCost: 9000,
    costMultiplier: 1.18,
    output: { gforce: 620, zoomies: 4e8 },
  },

  // --- Act 4 extras --------------------------------------------------------
  {
    id: 'p4-wormhole-junction',
    name: 'Wormhole Wings',
    description: 'A backstage corridor that exits before it enters. Produces everything, including paradoxes.',
    phase: 4,
    costCurrency: 'zoomies',
    baseCost: 6e16,
    costMultiplier: 1.16,
    output: { moonlight: 240, gforce: 2e6, tension: 2e6, zoomies: 6e13 },
  },
  {
    id: 'p4-galactic-tour-bus',
    name: 'Galactic Touring Company',
    description: 'Residency-holders tour the whole arm of the galaxy. Spend Comedy, reap Limelight & raves.',
    phase: 4,
    costCurrency: 'gforce',
    baseCost: 2e6,
    costMultiplier: 1.17,
    output: { moonlight: 40, bravos: 2e10, zoomies: 2e12 },
  },
  {
    id: 'p4-supernova-encore',
    name: 'Supernova Encore',
    description: 'For the curtain call, a star. Compounds its own Limelight in a blinding crescendo.',
    phase: 4,
    costCurrency: 'moonlight',
    baseCost: 800,
    costMultiplier: 1.18,
    output: { moonlight: 110, zoomies: 2e13 },
  },

  // --- Act 5: The Ouroboros (Echoes; some engines burn Limelight) ----------
  {
    id: 'p5-mirror-stage',
    name: 'Mirror Stage',
    description: 'A stage that reflects itself into the wings, into the seats, into next week. The first Echoes.',
    phase: 5,
    costCurrency: 'zoomies',
    baseCost: 1e18,
    costMultiplier: 1.17,
    output: { echoes: 1, zoomies: 2e15 },
  },
  {
    id: 'p5-hall-of-mirrors',
    name: 'Hall of Mirrors',
    description: 'Infinite reflections, infinite encores. Folds Limelight into pure recursion.',
    phase: 5,
    costCurrency: 'zoomies',
    baseCost: 9e18,
    costMultiplier: 1.17,
    output: { echoes: 7 },
    consumes: { moonlight: 60 },
  },
  {
    id: 'p5-recursive-troupe',
    name: 'Recursive Troupe',
    description: 'A cast that plays the audience watching the cast. Acclaim all the way down.',
    phase: 5,
    costCurrency: 'bravos',
    baseCost: 5e13,
    costMultiplier: 1.18,
    output: { echoes: 9, bravos: 4e12 },
  },
  {
    id: 'p5-fourth-wall',
    name: 'Fourth-Wall Breaker',
    description: 'Spend Echoes to address the audience directly — they rain back Buzz and fresh Limelight.',
    phase: 5,
    costCurrency: 'echoes',
    baseCost: 2000,
    costMultiplier: 1.18,
    output: { zoomies: 6e16, moonlight: 280 },
  },
  {
    id: 'p5-infinite-encore',
    name: 'Infinite Encore',
    description: 'It will not stop. It cannot stop. Each encore spawns more encores.',
    phase: 5,
    costCurrency: 'echoes',
    baseCost: 8000,
    costMultiplier: 1.18,
    output: { echoes: 95, zoomies: 4e17 },
  },
  {
    id: 'p5-ouroboros-coaster',
    name: 'The Ouroboros',
    description: 'The stage is a closed loop that is also the story that is also the stage. It produces everything, including itself.',
    phase: 5,
    costCurrency: 'zoomies',
    baseCost: 1e21,
    costMultiplier: 1.17,
    output: { echoes: 650, gforce: 1e8, tension: 1e8, zoomies: 8e18 },
  },
];

export const GENERATOR_META: Record<string, GeneratorDef> = Object.fromEntries(
  GENERATORS.map((g) => [g.id, g]),
);
